# Generated by Django 4.0.2 on 2022-04-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_blog_dateposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
