# Generated by Django 4.0.2 on 2022-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dateposted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
